pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
    - or:
      - "#approved-reviews-by>=1"
      - approved-reviews-by=@merbridge/docs-maintainers
    actions:
      merge:
        method: squash
  - name: Say hello to contributors
    conditions:
      - -draft
    actions:
      comment:
        message: |
           Welcome to the [Merbridge](https://github.com/merbridge) OpenSource Community!👏

           We're delighted to have you onboard 💘
